import Footer from "@/components/ui/Footer";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import { Inter, Indie_Flower } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const indie = Indie_Flower({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "FloraVision",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${indie.variable}`}>
      <body className="antialiased">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
